definitions:
  Error:
    properties:
      code:
        example: INVALID_ARGUMENT
        type: string
      message:
        example: invalid request body
        type: string
      meta:
        additionalProperties:
          type: string
        example:
          error: invalid_length
          field: username
        type: object
    type: object
  LoginInput:
    properties:
      password:
        example: echo_password
        maxLength: 64
        minLength: 8
        type: string
      username:
        example: echo_username
        maxLength: 255
        minLength: 6
        type: string
    required:
    - password
    - username
    type: object
  LoginOutput:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
      access_token_expires_at:
        example: "2026-04-27T12:00:00Z"
        type: string
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.refresh
        type: string
      refresh_token_expires_at:
        example: "2026-05-27T12:00:00Z"
        type: string
    type: object
  RegisterInput:
    properties:
      password:
        example: echo_password
        maxLength: 64
        minLength: 8
        type: string
      username:
        example: echo_username
        maxLength: 255
        minLength: 6
        type: string
    required:
    - password
    - username
    type: object
  RegisterOutput:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
      access_token_expires_at:
        example: "2026-04-27T12:00:00Z"
        type: string
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.refresh
        type: string
      refresh_token_expires_at:
        example: "2026-05-27T12:00:00Z"
        type: string
    type: object
info:
  contact:
    email: info@toppira.com
    name: Ali Moradi
    url: toppira.com/support
  description: Echo is a social media platform where people can freely share their
    feelings without being judged.
  title: Echo Swagger Document
  version: 0.0.1
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user using username and password and returns access
        and refresh tokens.
      parameters:
      - description: User login credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/LoginOutput'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/Error'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      summary: Authenticate user
      tags:
      - Authentication
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new user using username and password, and returns access/refresh
        tokens.
      parameters:
      - description: User registration input
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/RegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/RegisterOutput'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/Error'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/Error'
        "409":
          description: Duplicate username
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      summary: Register a new user account
      tags:
      - Authentication
swagger: "2.0"
